# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smart Photo Kit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart Photo Kit
pod 'Brightroom/Engine'
pod 'Brightroom/UI-Classic'
pod 'Brightroom/UI-Crop'
pod 'FMPhotoPicker', '~> 1.3.0'
pod 'SnapKit', '~> 5.0.0'
pod "JLStickerTextView", :git =>
"https://github.com/Textcat/JLStickerTextView.git"
pod 'StickerView'
pod 'SwiftyJSON', '~> 4.0'
pod 'Kingfisher', '~> 7.0'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
pod 'PullToDismiss', '~> 2.2'
end
